import type { RelatedLink } from '@/app/components/RelatedServices';

export interface BoroughData {
  name: string;
  slug: string;
  postcode: string;
  metaTitle: string;
  metaDescription: string;
  heroTagline: string;
  heroDescription: string;
  contentTitle: string;
  contentParagraphs: string[];
  landmarks: string[];
  corporateHQs: string[];
  nearestAirport: string;
  nearestAirportSlug: string;
  faqs: { q: string; a: string }[];
  relatedLinks: RelatedLink[];
}

export const boroughs: Record<string, BoroughData> = {
  'canary-wharf': {
    name: 'Canary Wharf',
    slug: 'canary-wharf',
    postcode: 'E14',
    metaTitle: 'Chauffeur Service Canary Wharf | Executive Car Hire E14',
    metaDescription: 'Premium chauffeur service in Canary Wharf. S-Class & V-Class hire for corporate travel, airport transfers, and evening events in E14.',
    heroTagline: 'Canary Wharf',
    heroDescription: 'Executive chauffeur services for London\'s financial district. Serving One Canada Square, Barclays HQ, and the Docklands business community.',
    contentTitle: 'The Financial',
    contentParagraphs: [
      'Canary Wharf is the heartbeat of London\'s financial sector. Our chauffeurs navigate the estate\'s one-way systems and security barriers with precision, delivering you to your building entrance on time.',
      'Whether you need a morning pickup from your Docklands apartment, a transfer to City Airport for a European day-trip, or an evening ride to a client dinner, we provide a seamless, professional service.',
    ],
    landmarks: ['One Canada Square', 'Crossrail Place', 'Jubilee Park', 'Museum of London Docklands'],
    corporateHQs: ['Barclays', 'HSBC', 'JP Morgan', 'Citigroup', 'Credit Suisse'],
    nearestAirport: 'London City Airport',
    nearestAirportSlug: '/landing/airport/london-city-airport',
    faqs: [
      { q: 'Can you collect from inside the Canary Wharf estate?', a: 'Yes. Our chauffeurs are familiar with the estate\'s loading bays and drop-off points for every tower.' },
      { q: 'How close is London City Airport?', a: 'London City Airport is approximately 10 minutes from Canary Wharf. We offer fixed-rate transfers from £125.' },
    ],
    relatedLinks: [
      { title: 'City Airport Transfers', href: '/landing/airport/london-city-airport', description: 'Fixed-rate transfers from Canary Wharf to LCY.' },
      { title: 'Mercedes S-Class', href: '/mercedes-s-class-chauffeur', description: 'Our flagship executive saloon.' },
      { title: 'Corporate Travel', href: '/corporate-travel-chauffeur', description: 'Dedicated corporate account services.' },
      { title: 'Chauffeur City of London', href: '/chauffeur-city-of-london', description: 'Service in the Square Mile.' },
    ],
  },
  'westminster': {
    name: 'Westminster',
    slug: 'westminster',
    postcode: 'SW1',
    metaTitle: 'Chauffeur Service Westminster | Luxury Car Hire SW1',
    metaDescription: 'Premium chauffeur service in Westminster. Discreet luxury transport for Parliament, Whitehall, and Victoria. Licensed TfL operator.',
    heroTagline: 'Westminster',
    heroDescription: 'Discreet luxury transport in the heart of government. Serving Parliament, Whitehall, Buckingham Palace, and Victoria.',
    contentTitle: 'The Seat of',
    contentParagraphs: [
      'Westminster demands absolute discretion and reliability. Our chauffeurs understand the unique requirements of working around the Houses of Parliament, government buildings, and royal residences.',
      'From early morning ministerial pickups to late-night returns from state dinners, we provide a service that meets the exacting standards of SW1.',
    ],
    landmarks: ['Houses of Parliament', 'Westminster Abbey', 'Buckingham Palace', 'St James\'s Park'],
    corporateHQs: ['Channel 4', 'ITV', 'New Scotland Yard'],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'Can you navigate the security zones around Parliament?', a: 'Yes. Our chauffeurs are experienced with the restricted zones and know the approved drop-off points.' },
      { q: 'Do you offer NDA chauffeurs?', a: 'All our chauffeurs sign NDAs as standard. Additional security vetting is available on request.' },
    ],
    relatedLinks: [
      { title: 'Heathrow Transfers', href: '/landing/airport/heathrow', description: 'Fixed-rate transfers from Westminster.' },
      { title: 'Chauffeur Mayfair', href: '/chauffeur-mayfair', description: 'Service in neighbouring Mayfair.' },
      { title: 'Corporate Events', href: '/corporate-event-chauffeur', description: 'Multi-vehicle event coordination.' },
      { title: 'Rolls-Royce Ghost', href: '/rolls-royce-chauffeur', description: 'Ultimate prestige for state occasions.' },
    ],
  },
  'fulham': {
    name: 'Fulham',
    slug: 'fulham',
    postcode: 'SW6',
    metaTitle: 'Chauffeur Service Fulham | Luxury Car Hire SW6',
    metaDescription: 'Premium chauffeur service in Fulham. Airport transfers, school runs, and evening events from SW6. Professional and punctual.',
    heroTagline: 'Fulham',
    heroDescription: 'Professional chauffeur services for Fulham residents. Airport transfers, school runs, and evening events from SW6.',
    contentTitle: 'At Home in',
    contentParagraphs: [
      'Fulham is home to families and professionals who value reliability and discretion. Our chauffeurs know the school run routes, the best approaches to the King\'s Road, and the quickest paths to Heathrow.',
      'Whether you need a regular weekday service or a one-off airport transfer, we deliver the same consistent, high-quality experience every time.',
    ],
    landmarks: ['Craven Cottage', 'Bishop\'s Park', 'Hurlingham Club', 'Fulham Palace'],
    corporateHQs: [],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'Do you offer regular school run services?', a: 'Yes. We can arrange a regular daily service with the same chauffeur for consistency and trust.' },
      { q: 'How long to Heathrow from Fulham?', a: 'Approximately 30-40 minutes depending on traffic. We recommend allowing 60 minutes for international flights.' },
    ],
    relatedLinks: [
      { title: 'Heathrow Transfers', href: '/landing/airport/heathrow', description: 'Fixed-rate transfers from Fulham.' },
      { title: 'Chauffeur Chelsea', href: '/chauffeur-chelsea', description: 'Service in neighbouring Chelsea.' },
      { title: 'Mercedes V-Class', href: '/mercedes-v-class-chauffeur', description: 'Spacious family transport.' },
      { title: 'By the Hour', href: '/chauffeur-hire-by-the-hour', description: 'Flexible hourly hire for day trips.' },
    ],
  },
  'richmond': {
    name: 'Richmond',
    slug: 'richmond',
    postcode: 'TW9',
    metaTitle: 'Chauffeur Service Richmond | Luxury Car Hire TW9',
    metaDescription: 'Premium chauffeur service in Richmond. Airport transfers, day trips, and event transport from TW9 and Richmond upon Thames.',
    heroTagline: 'Richmond',
    heroDescription: 'Luxury chauffeur services for Richmond upon Thames. Airport transfers, day trips to the countryside, and evening events.',
    contentTitle: 'Riverside',
    contentParagraphs: [
      'Richmond combines the charm of the countryside with proximity to central London. Our chauffeurs provide the perfect bridge between the two — whether you are heading to the City, Heathrow, or a day out at Hampton Court.',
      'We understand the rhythms of Richmond life: Saturday mornings on the towpath, Sunday lunches at riverside pubs, and Monday mornings in the Square Mile.',
    ],
    landmarks: ['Richmond Park', 'Kew Gardens', 'Hampton Court Palace', 'Richmond Theatre'],
    corporateHQs: [],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'How far is Heathrow from Richmond?', a: 'Approximately 20-30 minutes. Richmond is one of the closest residential areas to Heathrow Airport.' },
      { q: 'Do you cover Twickenham and surrounding areas?', a: 'Yes. We serve all of Richmond upon Thames including Twickenham, Teddington, Hampton, and Ham.' },
    ],
    relatedLinks: [
      { title: 'Heathrow Transfers', href: '/landing/airport/heathrow', description: 'Quick fixed-rate transfers from Richmond.' },
      { title: 'Chauffeur Surrey', href: '/chauffeur-surrey', description: 'Service across the Surrey border.' },
      { title: 'Range Rover', href: '/range-rover-chauffeur', description: 'Ideal for countryside day trips.' },
      { title: 'Wimbledon Chauffeur', href: '/wimbledon-chauffeur', description: 'Championships transport from Richmond.' },
    ],
  },
  'hampstead': {
    name: 'Hampstead',
    slug: 'hampstead',
    postcode: 'NW3',
    metaTitle: 'Chauffeur Service Hampstead | Luxury Car Hire NW3',
    metaDescription: 'Premium chauffeur service in Hampstead. Discreet luxury transport for NW3 residents. Airport transfers and evening events.',
    heroTagline: 'Hampstead',
    heroDescription: 'Discreet luxury transport for Hampstead\'s residents. Airport transfers, evening events, and private travel from NW3.',
    contentTitle: 'Village',
    contentParagraphs: [
      'Hampstead\'s village charm and winding lanes require a chauffeur who knows the territory. Our drivers navigate the narrow streets of NW3 with confidence, collecting you from your doorstep without delay.',
      'From transfers to Heathrow via the A41 corridor to evening rides into Mayfair for dinner, we provide a quiet, professional service that matches Hampstead\'s character.',
    ],
    landmarks: ['Hampstead Heath', 'Kenwood House', 'Freud Museum', 'Flask Walk'],
    corporateHQs: [],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'Can you navigate Hampstead\'s narrow streets?', a: 'Yes. Our chauffeurs are familiar with Hampstead\'s one-way systems and residential parking restrictions.' },
      { q: 'How long to Heathrow from Hampstead?', a: 'Approximately 45-60 minutes depending on traffic. We recommend allowing 90 minutes for international flights.' },
    ],
    relatedLinks: [
      { title: 'Heathrow Transfers', href: '/landing/airport/heathrow', description: 'Fixed-rate transfers from Hampstead.' },
      { title: 'Chauffeur St John\'s Wood', href: '/chauffeur-st-johns-wood', description: 'Service in neighbouring St John\'s Wood.' },
      { title: 'Mercedes S-Class', href: '/mercedes-s-class-chauffeur', description: 'The perfect executive saloon.' },
      { title: 'By the Hour', href: '/chauffeur-hire-by-the-hour', description: 'Flexible hourly hire for day trips.' },
    ],
  },
  'notting-hill': {
    name: 'Notting Hill',
    slug: 'notting-hill',
    postcode: 'W11',
    metaTitle: 'Chauffeur Service Notting Hill | Luxury Car Hire W11',
    metaDescription: 'Premium chauffeur service in Notting Hill. Discreet luxury transport for W11. Airport transfers, shopping trips, and evening events.',
    heroTagline: 'Notting Hill',
    heroDescription: 'Luxury chauffeur services for Notting Hill. Portobello Road, Westbourne Grove, and Holland Park at your doorstep.',
    contentTitle: 'West London',
    contentParagraphs: [
      'Notting Hill blends bohemian culture with some of London\'s most valuable residential streets. Our chauffeurs provide a discreet, stylish service that matches the area\'s character.',
      'From Saturday morning trips to Portobello Market to evening transfers to Soho or the West End, we navigate W11\'s streets with ease.',
    ],
    landmarks: ['Portobello Road Market', 'Holland Park', 'Electric Cinema', 'Westbourne Grove'],
    corporateHQs: [],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'Can you handle Carnival weekend logistics?', a: 'Yes. Our chauffeurs know the road closures and alternative routes during Notting Hill Carnival.' },
      { q: 'Do you cover Holland Park and Ladbroke Grove?', a: 'Yes. We serve all of W11 and the surrounding postcodes.' },
    ],
    relatedLinks: [
      { title: 'Chauffeur Kensington', href: '/chauffeur-kensington', description: 'Service in neighbouring Kensington.' },
      { title: 'Heathrow Transfers', href: '/landing/airport/heathrow', description: 'Fixed-rate transfers from W11.' },
      { title: 'Personal Shopping', href: '/personal-shopping-concierge-london', description: 'Chauffeur-driven shopping trips.' },
      { title: 'Mercedes E-Class', href: '/mercedes-e-class-chauffeur', description: 'Comfortable and discreet.' },
    ],
  },
  'belgravia': {
    name: 'Belgravia',
    slug: 'belgravia',
    postcode: 'SW1X',
    metaTitle: 'Chauffeur Service Belgravia | Luxury Car Hire SW1',
    metaDescription: 'Premium chauffeur service in Belgravia. Ultra-discreet luxury transport for SW1X. Embassy transfers, private residences, and exclusive venues.',
    heroTagline: 'Belgravia',
    heroDescription: 'Ultra-discreet luxury transport in London\'s most exclusive residential quarter. Serving embassies, private residences, and Eaton Square.',
    contentTitle: 'Embassy',
    contentParagraphs: [
      'Belgravia sets the standard for discreet luxury. Our chauffeurs are accustomed to serving embassy staff, diplomatic convoys, and residents who demand absolute privacy.',
      'From Eaton Square to Chester Row, Elizabeth Street to Motcomb Street — we know every approach, every parking restriction, and every private entrance.',
    ],
    landmarks: ['Eaton Square', 'Belgrave Square', 'Elizabeth Street', 'Motcomb Street'],
    corporateHQs: ['Multiple Embassies', 'Grosvenor Estate'],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'Do you provide NDA chauffeurs?', a: 'All our chauffeurs sign NDAs as standard. Additional security vetting is available on request.' },
      { q: 'Can you coordinate with embassy security?', a: 'Yes. We regularly work with diplomatic security teams and can accommodate specific protocols.' },
    ],
    relatedLinks: [
      { title: 'Chauffeur Knightsbridge', href: '/chauffeur-knightsbridge', description: 'Service in neighbouring Knightsbridge.' },
      { title: 'Chauffeur Mayfair', href: '/chauffeur-mayfair', description: 'Service in neighbouring Mayfair.' },
      { title: 'Rolls-Royce Ghost', href: '/rolls-royce-chauffeur', description: 'Ultimate prestige transport.' },
      { title: 'Heathrow Transfers', href: '/landing/airport/heathrow', description: 'Fixed-rate transfers from Belgravia.' },
    ],
  },
  'wimbledon': {
    name: 'Wimbledon',
    slug: 'wimbledon',
    postcode: 'SW19',
    metaTitle: 'Chauffeur Service Wimbledon | Luxury Car Hire SW19',
    metaDescription: 'Premium chauffeur service in Wimbledon. Airport transfers, Championships transport, and daily chauffeur hire from SW19.',
    heroTagline: 'Wimbledon',
    heroDescription: 'Professional chauffeur services for Wimbledon Village and SW19. Year-round transport plus Championships day packages.',
    contentTitle: 'Village',
    contentParagraphs: [
      'Wimbledon Village is one of south-west London\'s most desirable addresses. Our chauffeurs provide a reliable daily service as well as specialist Championships transport during the summer.',
      'From the Village high street to Wimbledon Common, Southfields station to the All England Club — we know every road, every shortcut, and every parking approach.',
    ],
    landmarks: ['All England Lawn Tennis Club', 'Wimbledon Common', 'Wimbledon Village', 'Cannizaro Park'],
    corporateHQs: [],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'Do you provide Championships day transport?', a: 'Yes. We offer full-day packages including travel to/from the AELTC and waiting time. See our Wimbledon Chauffeur page.' },
      { q: 'How long to Gatwick from Wimbledon?', a: 'Approximately 40-50 minutes via the A24 or M23. We monitor traffic and choose the fastest route.' },
    ],
    relatedLinks: [
      { title: 'Wimbledon Championships', href: '/wimbledon-chauffeur', description: 'Event-day packages for the Championships.' },
      { title: 'Gatwick Transfers', href: '/landing/airport/gatwick', description: 'Fixed-rate transfers from SW19.' },
      { title: 'Chauffeur Richmond', href: '/chauffeur-richmond', description: 'Service in neighbouring Richmond.' },
      { title: 'Mercedes V-Class', href: '/mercedes-v-class-chauffeur', description: 'Spacious family transport.' },
    ],
  },
  'greenwich': {
    name: 'Greenwich',
    slug: 'greenwich',
    postcode: 'SE10',
    metaTitle: 'Chauffeur Service Greenwich | Luxury Car Hire SE10',
    metaDescription: 'Premium chauffeur service in Greenwich. Airport transfers, O2 Arena events, and luxury transport across SE10.',
    heroTagline: 'Greenwich',
    heroDescription: 'Luxury chauffeur services for Greenwich. O2 Arena events, Cutty Sark visits, and airport transfers from SE10.',
    contentTitle: 'Maritime',
    contentParagraphs: [
      'Greenwich blends maritime heritage with modern entertainment at the O2 Arena. Our chauffeurs serve both — from elegant transfers to the Royal Observatory to concert-night pickups from North Greenwich.',
      'We navigate the Blackwall Tunnel, the A2, and the local streets of SE10 daily, ensuring you arrive on time regardless of destination.',
    ],
    landmarks: ['O2 Arena', 'Cutty Sark', 'Royal Observatory', 'Greenwich Park'],
    corporateHQs: ['InterContinental London - The O2'],
    nearestAirport: 'London City Airport',
    nearestAirportSlug: '/landing/airport/london-city-airport',
    faqs: [
      { q: 'Do you cover O2 Arena events?', a: 'Yes. We provide pre-booked pickups and drop-offs for all O2 events, avoiding the taxi queue.' },
      { q: 'How close is City Airport?', a: 'London City Airport is approximately 15 minutes from Greenwich via the A102.' },
    ],
    relatedLinks: [
      { title: 'City Airport Transfers', href: '/landing/airport/london-city-airport', description: 'Quick transfers from Greenwich to LCY.' },
      { title: 'Chauffeur Canary Wharf', href: '/chauffeur-canary-wharf', description: 'Service in neighbouring Canary Wharf.' },
      { title: 'Mercedes E-Class', href: '/mercedes-e-class-chauffeur', description: 'Comfortable executive saloon.' },
      { title: 'Hire by the Hour', href: '/chauffeur-hire-by-the-hour', description: 'Flexible hourly chauffeur hire.' },
    ],
  },
  'st-johns-wood': {
    name: 'St John\'s Wood',
    slug: 'st-johns-wood',
    postcode: 'NW8',
    metaTitle: 'Chauffeur Service St John\'s Wood | Luxury Car Hire NW8',
    metaDescription: 'Premium chauffeur service in St John\'s Wood. Discreet luxury transport for NW8. Lord\'s Cricket Ground transfers and airport pickups.',
    heroTagline: 'St John\'s Wood',
    heroDescription: 'Discreet luxury transport for St John\'s Wood. Serving Lord\'s Cricket Ground, Abbey Road, and the residential streets of NW8.',
    contentTitle: 'Exclusive',
    contentParagraphs: [
      'St John\'s Wood is one of London\'s most exclusive residential enclaves. Our chauffeurs provide a quiet, professional service that respects the area\'s privacy and tranquility.',
      'From match-day transfers to Lord\'s to morning commutes into the City, we deliver a consistent, high-quality experience for NW8 residents.',
    ],
    landmarks: ['Lord\'s Cricket Ground', 'Abbey Road Studios', 'Regent\'s Park', 'Primrose Hill'],
    corporateHQs: [],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'Do you provide Lord\'s match-day transport?', a: 'Yes. We offer pre-booked pickups and drop-offs for all Lord\'s fixtures, including Test matches and finals.' },
      { q: 'Can you do daily commutes?', a: 'Absolutely. We offer regular daily services with the same chauffeur for consistency.' },
    ],
    relatedLinks: [
      { title: 'Heathrow Transfers', href: '/landing/airport/heathrow', description: 'Fixed-rate transfers from NW8.' },
      { title: 'Chauffeur Hampstead', href: '/chauffeur-hampstead', description: 'Service in neighbouring Hampstead.' },
      { title: 'Mercedes S-Class', href: '/mercedes-s-class-chauffeur', description: 'The executive benchmark.' },
      { title: 'Corporate Travel', href: '/corporate-travel-chauffeur', description: 'Dedicated corporate accounts.' },
    ],
  },
  'battersea': {
    name: 'Battersea',
    slug: 'battersea',
    postcode: 'SW11',
    metaTitle: 'Chauffeur Service Battersea | Luxury Car Hire SW11',
    metaDescription: 'Premium chauffeur service in Battersea. Airport transfers, Battersea Power Station, and heliport transfers from SW11.',
    heroTagline: 'Battersea',
    heroDescription: 'Luxury chauffeur services for Battersea. Power Station, heliport transfers, and airport pickups from SW11.',
    contentTitle: 'Riverside',
    contentParagraphs: [
      'Battersea has transformed into one of London\'s most exciting residential areas. Our chauffeurs serve the Power Station development, the riverside apartments, and the Battersea Heliport.',
      'Whether you need a heliport transfer, an airport pickup, or a daily commute into the City, we provide a premium service from SW11.',
    ],
    landmarks: ['Battersea Power Station', 'Battersea Park', 'Battersea Heliport', 'Peace Pagoda'],
    corporateHQs: ['Apple Battersea'],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'Do you cover Battersea Heliport transfers?', a: 'Yes. See our dedicated Battersea Heliport Chauffeur page for details.' },
      { q: 'Can you collect from Battersea Power Station?', a: 'Yes. Our chauffeurs know the development\'s access points and drop-off areas.' },
    ],
    relatedLinks: [
      { title: 'Battersea Heliport', href: '/battersea-heliport-chauffeur', description: 'Dedicated heliport transfer service.' },
      { title: 'Chauffeur Chelsea', href: '/chauffeur-chelsea', description: 'Service across the river in Chelsea.' },
      { title: 'Heathrow Transfers', href: '/landing/airport/heathrow', description: 'Fixed-rate transfers from Battersea.' },
      { title: 'Mercedes EQV', href: '/mercedes-eqv-chauffeur', description: 'Electric luxury for eco-conscious travel.' },
    ],
  },
  'islington': {
    name: 'Islington',
    slug: 'islington',
    postcode: 'N1',
    metaTitle: 'Chauffeur Service Islington | Luxury Car Hire N1',
    metaDescription: 'Premium chauffeur service in Islington. Airport transfers, business travel, and evening events from N1.',
    heroTagline: 'Islington',
    heroDescription: 'Professional chauffeur services for Islington. Upper Street, Angel, and the business community of N1.',
    contentTitle: 'North London',
    contentParagraphs: [
      'Islington sits at the crossroads of north London\'s creative and business communities. Our chauffeurs serve the tech startups of Old Street, the theatres of Upper Street, and the residential streets of Barnsbury.',
      'From City Airport transfers via the A1 to Heathrow pickups via the Westway, we know the fastest routes out of N1 at every time of day.',
    ],
    landmarks: ['Upper Street', 'Sadler\'s Wells', 'Business Design Centre', 'Angel'],
    corporateHQs: [],
    nearestAirport: 'London City Airport',
    nearestAirportSlug: '/landing/airport/london-city-airport',
    faqs: [
      { q: 'How long to City Airport from Islington?', a: 'Approximately 20-25 minutes via the A1 and Limehouse Link.' },
      { q: 'Do you cover Clerkenwell and Farringdon?', a: 'Yes. We serve all of N1 and EC1 including Clerkenwell, Farringdon, and Old Street.' },
    ],
    relatedLinks: [
      { title: 'City Airport Transfers', href: '/landing/airport/london-city-airport', description: 'Fixed-rate transfers from Islington.' },
      { title: 'Chauffeur City of London', href: '/chauffeur-city-of-london', description: 'Service in the Square Mile.' },
      { title: 'Mercedes E-Class', href: '/mercedes-e-class-chauffeur', description: 'Professional and comfortable.' },
      { title: 'Corporate Travel', href: '/corporate-travel-chauffeur', description: 'Dedicated business accounts.' },
    ],
  },
  'city-of-london': {
    name: 'City of London',
    slug: 'city-of-london',
    postcode: 'EC',
    metaTitle: 'Chauffeur Service City of London | Executive Car Hire EC',
    metaDescription: 'Premium chauffeur service in the City of London. Executive transport for the Square Mile. Bank, Liverpool Street, and Barbican.',
    heroTagline: 'City of London',
    heroDescription: 'Executive chauffeur services for the Square Mile. Serving Bank, Liverpool Street, Moorgate, and the Barbican.',
    contentTitle: 'The Square',
    contentParagraphs: [
      'The City of London operates at a pace that demands punctuality and precision. Our chauffeurs understand the congestion charge zone, the one-way systems, and the loading restrictions that govern the Square Mile.',
      'From early morning pickups at Liverpool Street to late-night returns from client entertaining, we provide a reliable executive service for the City\'s professionals.',
    ],
    landmarks: ['Bank of England', 'St Paul\'s Cathedral', 'Barbican Centre', 'Tower of London'],
    corporateHQs: ['Lloyd\'s of London', 'Bank of England', 'Goldman Sachs', 'Deutsche Bank'],
    nearestAirport: 'London City Airport',
    nearestAirportSlug: '/landing/airport/london-city-airport',
    faqs: [
      { q: 'Do you know the City\'s loading restrictions?', a: 'Yes. Our chauffeurs are fully briefed on the City\'s time-restricted loading bays and drop-off points.' },
      { q: 'Can you wait in the City during meetings?', a: 'Yes. We use approved parking locations and are ready when you are. Hourly hire is available.' },
    ],
    relatedLinks: [
      { title: 'City Airport Transfers', href: '/landing/airport/london-city-airport', description: 'Direct transfers from the Square Mile.' },
      { title: 'Chauffeur Canary Wharf', href: '/chauffeur-canary-wharf', description: 'Service in Docklands.' },
      { title: 'Corporate Travel', href: '/corporate-travel-chauffeur', description: 'Dedicated corporate account services.' },
      { title: 'Mercedes S-Class', href: '/mercedes-s-class-chauffeur', description: 'The flagship executive saloon.' },
    ],
  },
  'south-kensington': {
    name: 'South Kensington',
    slug: 'south-kensington',
    postcode: 'SW7',
    metaTitle: 'Chauffeur Service South Kensington | Luxury Car Hire SW7',
    metaDescription: 'Premium chauffeur service in South Kensington. Museum district transport, airport transfers, and school runs from SW7.',
    heroTagline: 'South Kensington',
    heroDescription: 'Luxury chauffeur services for South Kensington. The museum district, Cromwell Road, and the residential streets of SW7.',
    contentTitle: 'Cultural',
    contentParagraphs: [
      'South Kensington is London\'s cultural heart, home to the V&A, Natural History Museum, and Royal Albert Hall. Our chauffeurs navigate the busy museum district and residential streets of SW7 with ease.',
      'Whether you need a school run to one of SW7\'s prestigious schools, an airport transfer from your Onslow Gardens apartment, or an evening ride to the Royal Albert Hall, we provide a seamless service.',
    ],
    landmarks: ['V&A Museum', 'Natural History Museum', 'Royal Albert Hall', 'Science Museum'],
    corporateHQs: ['Institut Francais', 'Imperial College London'],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'Can you do school runs in South Kensington?', a: 'Yes. We serve all major schools in SW7 and can arrange regular daily services.' },
      { q: 'How long to Heathrow?', a: 'Approximately 35-45 minutes via the A4 corridor. We recommend allowing 60 minutes for international flights.' },
    ],
    relatedLinks: [
      { title: 'Chauffeur Kensington', href: '/chauffeur-kensington', description: 'Service in neighbouring Kensington.' },
      { title: 'Chauffeur Chelsea', href: '/chauffeur-chelsea', description: 'Service in neighbouring Chelsea.' },
      { title: 'Heathrow Transfers', href: '/landing/airport/heathrow', description: 'Fixed-rate transfers from SW7.' },
      { title: 'Mercedes V-Class', href: '/mercedes-v-class-chauffeur', description: 'Spacious family transport.' },
    ],
  },
  'marylebone': {
    name: 'Marylebone',
    slug: 'marylebone',
    postcode: 'W1U',
    metaTitle: 'Chauffeur Service Marylebone | Luxury Car Hire W1',
    metaDescription: 'Premium chauffeur service in Marylebone. Harley Street medical transfers, station pickups, and luxury transport from W1.',
    heroTagline: 'Marylebone',
    heroDescription: 'Professional chauffeur services for Marylebone. Harley Street medical transfers, Marylebone station pickups, and W1 luxury transport.',
    contentTitle: 'Medical',
    contentParagraphs: [
      'Marylebone is home to Harley Street\'s world-renowned medical practices. Our chauffeurs provide discreet, comfortable transport for patients, consultants, and their families.',
      'Beyond Harley Street, we serve the boutique shops of Marylebone High Street, the residential streets of W1U, and provide efficient transfers from Marylebone station.',
    ],
    landmarks: ['Harley Street', 'Marylebone High Street', 'Regent\'s Park', 'Madame Tussauds'],
    corporateHQs: ['Harley Street Medical District'],
    nearestAirport: 'Heathrow',
    nearestAirportSlug: '/landing/airport/heathrow',
    faqs: [
      { q: 'Do you provide medical appointment transfers?', a: 'Yes. We regularly transport patients to and from Harley Street appointments, with waiting time included.' },
      { q: 'Can you collect from Marylebone station?', a: 'Yes. We meet you at the station exit and handle your luggage.' },
    ],
    relatedLinks: [
      { title: 'Chauffeur Mayfair', href: '/chauffeur-mayfair', description: 'Service in neighbouring Mayfair.' },
      { title: 'Heathrow Transfers', href: '/landing/airport/heathrow', description: 'Fixed-rate transfers from Marylebone.' },
      { title: 'Mercedes S-Class', href: '/mercedes-s-class-chauffeur', description: 'Comfortable medical transport.' },
      { title: 'By the Hour', href: '/chauffeur-hire-by-the-hour', description: 'Flexible hourly hire for appointments.' },
    ],
  },
};

export function getAllBoroughs() {
  return Object.keys(boroughs).map(borough => ({ borough }));
}
